#include "stdafx.h"
#include "CompileInterfaces.h"
#include "CompileContext.h"
#include "CrystalScriptStream.h"
#include "SyntaxParser.h"
#include "ScriptOMAll.h"
#include "GameSession.h"
#include "ResourceMap.h"
#include "ResourceEntity.h"
#include "ResourceBlob.h"
#include "Text.h"
#include "SCO.h"
#include "ScriptText.h"
#include "format.h"
#include <fstream>

// The script compile, with no GUI: everything comes from the GameSession.

using namespace std;

bool CompileLog::HasErrors()
{
	return _cErrors > 0;
}

void CompileLog::SummarizeAndReportErrors()
{
	stringstream summaryMessage;
	summaryMessage << _cErrors << " errors, " << _cWarnings << " warnings.";
	ReportResult(CompileResult(summaryMessage.str()));
}

void CompileLog::CalculateErrors()
{
	// Calculate errors;
	_cErrors += (int)count_if(_compileResults.begin(), _compileResults.end(), mem_fun_ref(&CompileResult::IsError));
	_cWarnings += (int)count_if(_compileResults.begin(), _compileResults.end(), mem_fun_ref(&CompileResult::IsWarning));
}

std::unique_ptr<sci::Script> SimpleCompile(const std::unordered_set<std::string> &preProcessorDefines, CompileLog &log, ScriptId &scriptId, bool addCommentsToOM)
{
	std::unique_ptr<sci::Script> script = make_unique<sci::Script>();
	script->SetScriptId(scriptId);
	sci::Result<ScriptText> text = LoadScriptText(scriptId.GetFullPath());
	if (text)
	{
		CScriptStreamLimiter limiter(*text);
		CCrystalScriptStream stream(&limiter);
		if (SyntaxParser_Parse(*script, stream, preProcessorDefines, &log, addCommentsToOM))
		{

		}
	}
	log.CalculateErrors();
	return script;
}

std::unique_ptr<sci::Script> SimpleCompile(const SCIVersion &version, CompileLog &log, ScriptId &scriptId, bool addCommentsToOM)
{
	return SimpleCompile(PreProcessorDefinesFromSCIVersion(version), log, scriptId, addCommentsToOM);
}

bool NewCompileScript(GameSession &session, CompileResults &results, CompileLog &log, CompileTables &tables, PrecompiledHeaders &headers, ScriptId &script)
{
	bool fRet = false;
	CResourceMap &resourceMap = session.ResourceMap();
	const GameFolderHelper &helper = session.Helper();

	g_compileIOTimer.Start();

	sci::Result<ScriptText> text = LoadScriptText(script.GetFullPath());
	if (text)
	{
		g_compileIOTimer.Stop();

		CScriptStreamLimiter limiter(*text);
		CCrystalScriptStream stream(&limiter);

		std::unique_ptr<sci::Script> pScript = std::make_unique<sci::Script>(script);
		// A (GetPoly "name") statement reads the game's polygon files.
		pScript->SetPolyFolder(helper.GetPolyFolder());

		if (SyntaxParser_Parse(*pScript, stream, PreProcessorDefinesFromSCIVersion(session.Version()), &log))
		{
			if (script.GetResourceNumber() != pScript->GetScriptNumber())
			{
				log.ReportResult(
					CompileResult(fmt::format("Script {0} ({1}) declared itself as resource {2}", script.GetResourceNumber(), script.GetTitle(), pScript->GetScriptNumber()),
					CompileResult::CompileResultType::CRT_Warning));
			}

			// Compile and save script resource.
			// Compile our own script!
			if (GenerateScriptResource(session, *pScript, headers, tables, results, helper.GetGenerateDebugInfo()))
			{
				WORD wNum = results.GetScriptNumber();

				// Save the text resource - but only if it's different than what's there (otherwise needless text resource turds pile up)
				if (!results.GetTextComponent().Texts.empty())
				{
					ResourceEntity &textResource = results.GetTextResource();
					// Mark it as being auto-generated by a script compile:
					textResource.GetComponent<TextComponent>().AddString(AutoGenTextSentinel);

					auto existingTextResource = resourceMap.CreateResourceFromNumber(ResourceType::Text, textResource.ResourceNumber);
					if (!existingTextResource || !existingTextResource->GetComponent<TextComponent>().AreTextsEqual(textResource.GetComponent<TextComponent>()))
					{
						resourceMap.AppendResource(textResource, session.Version().DefaultVolumeFile, textResource.ResourceNumber, "");
						log.ReportResult(
							CompileResult(fmt::format("Text resource {1} changed. Added {0} entries.", results.GetTextComponent().Texts.size(), textResource.ResourceNumber),
							CompileResult::CompileResultType::CRT_Message)
							);
					} // Else don't save.
				}

				// Update any tables that need to be modified (global class table, selector table)

				// Save the script resource
				std::vector<BYTE> &output = results.GetScriptResource();
				resourceMap.AppendResource(ResourceBlob(helper, nullptr, ResourceType::Script, output, helper.Version.DefaultVolumeFile, wNum, NoBase36, helper.Version, helper.GetDefaultSaveSourceFlags()));

				std::vector<BYTE> &outputHep = results.GetHeapResource();
				if (!outputHep.empty())
				{
					resourceMap.AppendResource(ResourceBlob(helper, nullptr, ResourceType::Heap, outputHep, helper.Version.DefaultVolumeFile, wNum, NoBase36, helper.Version, helper.GetDefaultSaveSourceFlags()));
				}

				// Save the corresponding sco file.
				g_compileIOTimer.Start();
				g_compileObjFileTimer.Start();
				CSCOFile &sco = results.GetSCO();
				{
					SaveSCOFile(helper, sco, script);
				}
				g_compileObjFileTimer.Stop();
				g_compileDebugSymbolTimer.Start();
				if (!results.GetDebugInfo().empty())
				{
					// Save debug information.
					std::string scdFileName = helper.GetScriptDebugFileName(script.GetResourceNumber());
					ofstream scdFile(scdFileName.c_str(), ios::out | ios::binary);
					// REVIEW: yucky
					scdFile.write((const char *)&results.GetDebugInfo()[0], (std::streamsize)results.GetDebugInfo().size());
					scdFile.close();
				}
				g_compileDebugSymbolTimer.Stop();
				g_compileIOTimer.Stop();
				fRet = true;
			}
		}
		log.CalculateErrors();
	}
	return fRet;
}
