name: Build SCI Companion

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Kawa]
        platform: [Win32]

    steps:
    - uses: actions/checkout@v4

    # Add msbuild action
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    # Install VS 2017 (Platform Tools v141), and Windows 11 SDK. See: https://stackoverflow.com/a/74673996/953887
    - name: Install MSVC 2017 (v141) and Windows 11 SDK
      shell: powershell
      run: |
        $VS_BTOOLS_EXE="vs_buildtools.exe"
        $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
        Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
        Start-Process -FilePath ./vs_buildtools.exe -ArgumentList `
        "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64", `
        "--add", "Microsoft.VisualStudio.Component.VC.v141.ATL", `
        "--add", "Microsoft.VisualStudio.Component.VC.v141.MFC", `
        "--add", "Microsoft.VisualStudio.Component.Windows11SDK.26100", `
        "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru

    # Compile the solution
    - name: Build
      run: |
        msbuild SCICompanion.sln /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:VisualStudioVersion=15.0 /p:WindowsTargetPlatformVersion=10.0.26100.0
        mkdir artifacts
        copy ${{ matrix.configuration }}\*.exe artifacts
        Get-ChildItem ${{ matrix.configuration }} -Directory |
        Foreach-Object {
            Copy-Item -Path $_.FullName -Destination "artifacts" -recurse
        }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SCICompanion-${{ matrix.configuration }}-${{ matrix.platform }}-${{ github.sha }}
        path: artifacts
